"""Accept only the exact medium bundle with reviewable fidelity evidence."""
from pathlib import Path
import argparse,json
import numpy as np
from environment.persistence.checkpoint import file_hash
from environment.models.artifact_loader import ArtifactLoader
parser=argparse.ArgumentParser();parser.add_argument('--metrics',type=Path,required=True);parser.add_argument('--pytest-log',type=Path,required=True);parser.add_argument('--pytest-result',type=Path,required=True);parser.add_argument('--output',type=Path,required=True);args=parser.parse_args()
A=Path('data/output/finalization-validation');D=args.metrics;m=json.loads((D/'metrics.json').read_text());o=json.loads((D/'observable-activity.json').read_text());c=json.loads((D/'carry-uncertainty.json').read_text());h=json.loads((A/'historical-v3-subpop/subpopulation-validation.json').read_text());inv=json.loads((A/'medium'/m['run_id']/'final-invariants.json').read_text())
test_result=json.loads(args.pytest_result.read_text())
checks={'correctness':inv['status']=='PASS' and inv['committed_days']==31,'no_new_application_overactivity':all(z['corrected']['events_per_app']<=z['historical_weekday_adjusted']['events_per_app'] for z in m['age'].values()),'observable_activity_all_subpopulations':all(v['combined_app_cluster_95pct_difference'][0]<=0<=v['combined_app_cluster_95pct_difference'][1] for z in o['age'].values() for v in z.values()),'eligible_ptp_all_subpopulations':all(v['ptp_difference_95pct_interval'][0]<=0<=v['ptp_difference_95pct_interval'][1] for z in o['age'].values() for v in z.values()),'matched_carry_predictive_interval':c['within_predictive_interval'],'historical_carry_temporal_validation':h['carry_temporal_validation']['observed_minus_predicted_app_cluster_95pct_interval'][0]<=0<=h['carry_temporal_validation']['observed_minus_predicted_app_cluster_95pct_interval'][1],'no_inflated_loop_counts':all(m['age']['7']['corrected']['loops'][k]['mean_per_app']<=v['mean_per_app'] for k,v in m['age']['7']['historical_weekday_adjusted']['loops'].items()),'full_pytest':test_result['exit_code']==0 and test_result['passed_test_cases']==90 and test_result['log_sha256']==file_hash(args.pytest_log),'frozen_assets_unchanged':all(file_hash(Path(p))==sha for p,sha in json.loads((A/'frozen-before.json').read_text()).items())}
# Timing is assessed against the unchanged corrected-v1 baseline.
t=m['timing'];old=json.loads(Path('data/output/corrected-v1-validation/phase2-metrics.json').read_text());baseline=old['timing']['corrected']['application']['seconds'];truth=t['historical']['application']['seconds'];new=t['corrected']['application']['seconds'];checks['timing_improves_major_quantile_errors']=all(abs(new[k]-truth[k])<=abs(baseline[k]-truth[k]) for k in ['median','p90','p95','p99'])
identity=json.loads((A/'returning-identity-validation.json').read_text());checks['returning_identity_share_and_lifecycles']=identity['medium']['within_interval'] and identity['full_schedule']['within_interval'] and identity['lifecycle_identity_checks']=='PASS'
checks['eligible_prior_gap_and_outcome']=identity['eligible_donor_validation']['status']=='PASS'
checks['raw_activity_no_overactivity_each_subpopulation']=all(v['corrected']['events_per_app']<=v['historical_weekday_adjusted']['events_per_app'] for ages in m['returning']['medium_subpopulations'].values() for v in ages.values())
validated=ArtifactLoader('artifacts/gold_events_v3').validate()
checks['artifact_validation']=len(validated)==31
checks['run_uses_exact_candidate_inputs']=json.loads((A/'medium'/m['run_id']/'run_manifest.json').read_text())['artifact_hashes']==validated
checks['subpopulation_loop_counts_not_inflated']=all(v['corrected']['loops'][k]['mean_per_app']<=v['historical_weekday_adjusted'][k+'_per_app'] for ages in m['returning']['medium_subpopulations'].values() for v in [ages['7']] for k in v['corrected']['loops'] if k+'_per_app' in v['historical_weekday_adjusted'])
checks['only_historically_supported_bursts']=not json.loads((D/'burst-validation.json').read_text())['unsupported_simulated_groups']
result=dict(status='PASS' if all(checks.values()) else 'FAIL',run_id=m['run_id'],bundle_sha256=file_hash(Path('artifacts/gold_events_v3/manifest.json')),checks=checks,raw_phase2_first7_events_per_app=m['age']['7']['historical_weekday_adjusted']['events_per_app'],simulated_first7_events_per_app=m['age']['7']['corrected']['events_per_app'],interpretation='Raw Phase 2 benchmarks are preserved. Lower activity/PTP is assessed separately against deterministic guard-observable historical paths because missing prerequisite telemetry cannot be emitted by weakening guards.',carry=c,limitations=['Original April1 Wednesday carry benchmark remains higher than the same-weekday benchmark','Rare-event carry uncertainty uses a cluster-sandwich normal approximation','Raw all-entrant PTP remains lower because of prerequisite observability','Rare >24h gaps remain underrepresented; core timing and major transitions improve','April is validation/model-selection evidence, not an untouched future test'])
args.output.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if result['status']!='PASS':raise SystemExit(1)
