"""Phase 2 Friday/depth benchmark with application-cluster predictive uncertainty."""
import argparse,json,gzip
from pathlib import Path
import numpy as np,pandas as pd
parser=argparse.ArgumentParser();parser.add_argument('metrics',type=Path);args=parser.parse_args();m=json.loads(args.metrics.read_text());h=pd.read_parquet(args.metrics.parent/'historical_pl_terminal_safe.parquet');h=h.sort_values(['application_id','event_datetime'],kind='stable').reset_index(drop=True);life=pd.read_parquet('artifacts/gold_events_v3/application_lifecycle_state.parquet').dropna(subset=['context_id','application_created_at']);life['deadline']=life.application_created_at+pd.Timedelta(days=30);pt=h.loc[h.journey_substage.eq('Push to Partner')].groupby('application_id').event_datetime.min()
def bins(x):
    x=x.copy();x['age']=pd.cut(x.age_days,[0,7,14,21,30],include_lowest=True).astype(str);x['silence']=pd.cut(x.silence_days,[-1,1,7,14,21,31]).astype(str);x['depth']=pd.cut(x.prior_count,[0,3,6,10,np.inf],include_lowest=True).astype(str);return x
rows=[]
for bound in pd.date_range('2026-03-06','2026-04-17',freq='7D'):
    before=h.loc[h.event_datetime.lt(bound)];prior=before.sort_values('event_datetime').drop_duplicates('application_id',keep='last')
    x=life.merge(prior[['application_id','event_datetime','journey_substage']],on='application_id');x=x.loc[x.application_created_at.lt(bound)&x.deadline.gt(bound)&x.deadline.le('2026-05-01')&~x.application_id.isin(pt.loc[pt.lt(bound)].index)].copy()
    x['prior_count']=x.application_id.map(before.groupby('application_id').size());x['age_days']=(bound-x.application_created_at).dt.total_seconds()/86400;x['silence_days']=(bound-x.event_datetime).dt.total_seconds()/86400;x['active']=x.application_id.isin(h.loc[h.event_datetime.ge(bound),'application_id']);rows.append(bins(x))
hist=pd.concat(rows,ignore_index=True);keys=['journey_substage','age','silence','depth'];rates=hist.groupby(keys).agg(opportunities=('active','size'),unique_apps=('application_id','nunique'),rate=('active','mean'))
snap=pd.read_parquet('artifacts/gold_events_v3/starting_snapshot.parquet');target=snap.merge(life[['application_id','application_created_at']],on='application_id');target['age_days']=(pd.Timestamp('2026-05-01')-target.application_created_at).dt.total_seconds()/86400;target['silence_days']=(pd.Timestamp('2026-05-01')-target.snapshot_event_datetime).dt.total_seconds()/86400;target['prior_count']=target.application_id.map(h.groupby('application_id').size());target=target.rename(columns={'snapshot_substage':'journey_substage'});target=bins(target).join(rates,on=keys);target=target.loc[target.unique_apps.ge(30)];counts=target.groupby(keys).size().rename('target_n');ref=hist.join(rates,on=keys).join(counts,on=keys).dropna(subset=['target_n']);ref['influence']=ref.target_n/ref.opportunities*(ref.active.astype(float)-ref.rate);influence=ref.groupby('application_id').influence.sum();estvar=float((influence**2).sum()*len(influence)/(len(influence)-1));expected=float(target.rate.sum());worldvar=float((target.rate*(1-target.rate)).sum());half=1.96*np.sqrt(estvar+worldvar);observed=m['carried']['matched_fridays_depth']['corrected']['observed_active']
result=dict(method='Same Phase 2 Friday/source/age/silence/depth strata; >=30 unique historical applications; cluster-sandwich estimation variance plus independent target-world Bernoulli variance',supported_apps=len(target),expected_active=expected,observed_active=observed,estimation_variance=estvar,world_variance=worldvar,approx_95pct_predictive_interval=[max(0.,expected-half),expected+half],within_predictive_interval=bool(max(0.,expected-half)<=observed<=expected+half),limitations=['Rare-event normal approximation; historical cluster uncertainty included','April1 original benchmark has a weekday mismatch and remains separately reported'])
assert abs(expected-m['carried']['matched_fridays_depth']['corrected']['expected_active'])<1e-8,(expected,m['carried']['matched_fridays_depth']['corrected']['expected_active'])
(args.metrics.parent/'carry-uncertainty.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
