"""Validate the historical identity mixture and retained prior-history properties."""
import argparse,json
from pathlib import Path
import numpy as np,pandas as pd
parser=argparse.ArgumentParser();parser.add_argument('--bundle',type=Path,default=Path('artifacts/gold_events_v3'));parser.add_argument('--output',type=Path,default=Path('data/output/finalization-validation/returning-identity-validation.json'));args=parser.parse_args();B=args.bundle;A=Path('data/output/finalization-validation');life=pd.read_parquet(B/'application_lifecycle_state.parquet').dropna(subset=['context_id','application_created_at']).sort_values(['context_id','application_created_at']);life['prior']=life.groupby('context_id').application_created_at.shift();life['prior_id']=life.groupby('context_id').application_id.shift();apr=life.loc[life.application_created_at.ge('2026-04-01')].copy();apr['returning']=(apr.application_created_at-apr.prior).dt.total_seconds().ge(30*86400);apr['weekday']=apr.application_created_at.dt.weekday;rates=apr.groupby('weekday').returning.agg(['size','mean']);a=pd.read_parquet(B/'may_application_arrivals.parquet');se=pd.read_parquet(A/'medium-final-metrics/simulated_pl.parquet');ids=set(se.loc[se.creation.ge('2026-05-01'),'application_id']);result={}
for name,x in [('medium',a.loc[a.application_id.isin(ids)]),('full_schedule',a)]:
    n=x.activation_datetime.dt.weekday.value_counts();expected=sum(n[k]*rates.loc[k,'mean'] for k in n.index);variance=sum((n[k]+n[k]**2/rates.loc[k,'size'])*rates.loc[k,'mean']*(1-rates.loc[k,'mean']) for k in n.index);count=int(x.customer_kind.eq('RETURNING_CUSTOMER').sum());half=1.96*np.sqrt(variance);result[name]=dict(apps=len(x),returning=count,share=count/len(x),weekday_adjusted_expected_returning=float(expected),predictive_95pct_interval=[float(expected-half),float(expected+half)],within_interval=bool(expected-half<=count<=expected+half))
r=a.loc[a.customer_kind.eq('RETURNING_CUSTOMER')];lookup=life.set_index('application_id');assert r.prior_application_id.isin(lookup.index).all();assert r.snapshot_context_id.is_unique;assert a.application_id.is_unique and not a.application_id.isin(lookup.index).any();assert (r.snapshot_context_id.to_numpy()==r.prior_application_id.map(lookup.context_id).to_numpy()).all();assert (r.activation_datetime-r.prior_application_id.map(lookup.application_created_at)).ge(pd.Timedelta(days=30)).all();result['historical_april']=dict(entrants=len(apr),returners=int(apr.returning.sum()),share=float(apr.returning.mean()));result['lifecycle_identity_checks']='PASS'
h=pd.read_parquet(A/'medium-final-metrics/historical_pl_terminal_safe.parquet');depth=h.groupby('application_id').size();last=h.groupby('application_id').event_datetime.max();ptp=h.loc[h.journey_substage.eq('Push to Partner')].groupby('application_id').event_datetime.min()
def quant(x):return dict(zip(['p10','p25','median','p75','p90','p95','p99'],map(float,pd.Series(x).dropna().quantile([.1,.25,.5,.75,.9,.95,.99]))))
props={}
for name,when,prior in [('historical_april',apr.loc[apr.returning,'application_created_at'],apr.loc[apr.returning,'prior_id']),('generated_may',r.activation_datetime,r.prior_application_id)]:
    birth=prior.map(lookup.application_created_at);terminal=prior.map(ptp).fillna(birth+pd.Timedelta(days=30));props[name]=dict(creation_gap_days=quant((when-birth).dt.total_seconds()/86400),gap_since_terminal_days=quant((when-terminal).dt.total_seconds()/86400),gap_since_last_event_days=quant((when-prior.map(last)).dt.total_seconds()/86400),prior_ptp_fraction=float(prior.isin(ptp.index).mean()),prior_observed_history_depth=quant(prior.map(depth)))
result['prior_history_properties']=props
# Independently check the selected donor against the available historical risk
# set, including outcomes and earlier May assignments. A sparse gap cell must
# never expand to arbitrary distant contexts.
valid=life.copy();valid['previous_creation']=valid.groupby('context_id').application_created_at.shift()
invalid=set(valid.loc[(valid.application_created_at-valid.previous_creation).dt.total_seconds().lt(30*86400),'context_id'])
latest=valid.drop_duplicates('context_id',keep='last');contexts=latest.context_id.to_numpy();births=latest.application_created_at.astype('int64').to_numpy();outcomes=latest.application_id.isin(ptp.index).to_numpy();used=np.isin(contexts,list(invalid));lookup_context=dict(zip(contexts,range(len(contexts))))
violations=0;outcome_mismatches=0;errors=[];nearest_errors=[];minimum_gaps=[];radii=[]
for row in r.sort_values(['activation_datetime','application_id'],kind='stable').itertuples(index=False):
    gaps=(pd.Timestamp(row.activation_datetime).value-births)/86400e9;eligible=(gaps>=30)&~used
    desired=eligible&(outcomes==bool(row.target_prior_ptp));pool=desired if desired.any() else eligible
    distances=np.abs(gaps[pool]-row.target_prior_gap_days);radius=max(3.,float(np.partition(distances,min(29,len(distances)-1))[min(29,len(distances)-1)]))
    i=lookup_context[row.snapshot_context_id];error=abs(gaps[i]-row.target_prior_gap_days)
    violations+=int(not pool[i] or error>radius+1e-9);outcome_mismatches+=int(outcomes[i]!=bool(row.target_prior_ptp));errors.append(error);nearest_errors.append(float(distances.min()));minimum_gaps.append(float(gaps[pool].min()));radii.append(radius);used[i]=True
result['eligible_donor_validation']=dict(status='PASS' if not violations and not outcome_mismatches else 'FAIL',unsupported_gap_selections=violations,prior_outcome_mismatches=outcome_mismatches,all_returners_checked=len(r),absolute_target_gap_error_days=quant(errors),nearest_available_gap_error_days=quant(nearest_errors),minimum_available_gap_days=quant(minimum_gaps),supported_radius_days=quant(radii),interpretation='Closest supported eligible historical neighborhood within sampled prior outcome; finite immutable March-April histories and no May context reuse constrain late-May gaps. Raw April gap quantiles are retained above, not treated as matched late-May risk sets.')
args.output.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
