"""Write a reviewable local report from completed validation evidence."""
import argparse,json
from pathlib import Path
import numpy as np,pandas as pd
parser=argparse.ArgumentParser();parser.add_argument('metrics',type=Path);parser.add_argument('run',type=Path);parser.add_argument('report',type=Path);parser.add_argument('--medium-candidate',action='store_true');parser.add_argument('--pytest-log',type=Path,default=Path('data/output/finalization-validation/gap-outcome-full-pytest.log'));parser.add_argument('--gate',type=Path,default=Path('data/output/finalization-validation/medium-gap-outcome-gate.json'));args=parser.parse_args();A=Path('data/output/finalization-validation');m=json.loads(args.metrics.read_text());old=json.loads(Path('data/output/corrected-v1-validation/phase2-metrics.json').read_text());inv=json.loads((args.run/'final-invariants.json').read_text());identity=json.loads((A/'returning-identity-validation.json').read_text());gate=json.loads(args.gate.read_text());observable=json.loads((args.metrics.parent/'observable-activity.json').read_text());ci=json.loads((args.metrics.parent/'carry-uncertainty.json').read_text());lines=[]
def add(x=''):lines.append(x)
def table(headers,rows):
 add('| '+' | '.join(headers)+' |');add('| '+' | '.join(['---']*len(headers))+' |')
 for row in rows:add('| '+' | '.join(map(str,row))+' |')
 add()
def f(x):return f'{x:.4f}'
add('# Corrected-v2 finalization evidence');add();add('Local, uncommitted validation package. Historical-only model fitting; no PostgreSQL/S3 writes or Transformer/RL integration. The completed full reference used the preserved pre-gap identity bundle. This corrected identity candidate has medium validation; final full validation is pending an explicit exception to the original ONE-run limit.');add()
add('## Version and runtime contract');add();add('`legacy-v2r2` and `corrected-v1` retain frozen v1/v2 assets. `corrected-v2` explicitly selects v3. Older defaults remain for compatibility; `config/corrected-v2.yaml` selects the new contract. The external interface is documented in `docs/corrected-v2-contract.md`.');add()
add('## Medium overactivity audit and mechanism fixes');add();add('The first medium candidate emitted 34,737 events: 34,415 new-application rows and 322 carried rows. First-seven-day events/application were 8.3822 versus the unchanged weekday-adjusted Phase 2 benchmark of 7.1375 (+17.4%). Repeated-substage counts were 2.1605 versus 1.4286 per application. Eventful application-days stayed close to history, identifying within-session overactivity. The candidate was rejected.');add();add('The natural cause-specific law censored PTP and then ran an independent PTP clock. Its competing-risk assumptions inflated repeated AIP/journey paths. The replacement models mutually exclusive next journey/eligible-terminal outcomes. Missing-prerequisite terminal mass remains inactive; guards are unchanged. Returning-customer history does not populate the new application\'s prerequisite flags. Separate historically fitted returning/new pools correct the population mixture.');add();add('Supported bursts contributed 893 same-time extra new rows in the rejected candidate, insufficient to explain the excess. Stage/global backoff accounted for 266 of 44,187 natural-law evaluations (<1%). Cached episode scheduling and WAIT segmentation tests exclude repeated polling redraws. No global event multiplier, probability scaling, forced loops, or jitter was introduced.');add();add('The accepted medium has 28,679 rows: 28,405 new and 274 carried, 4,096 arrivals, 13,007 carries, 45 carried applications active, 2,263 PTP, and 13,013 exact expiries. The final carry fix leaves every new Gold row and stochastic key identical to the preceding medium. Matched Friday/depth activity is 34 versus 47.86 expected, inside the 31.22–64.50 predictive interval.');add()
add('## Equal-age new application comparisons');add();add('The same Phase 2 population is independently reconstructed: 578,324 eligible events and 81,416 applications. Each horizon requires complete observation to that age. Weekday adjustment uses the simulated cohort distribution; no late arrivals with incomplete follow-up enter these comparisons.');add()
rows=[]
for d in ['1','3','7']:
 z=m['age'][d]
 for label,key in [('Historical weekday adjusted','historical_weekday_adjusted'),('Corrected-v2','corrected')]:
  v=z[key];rows.append([d,label,f(v['events_per_app']),f(v['eventful_appdays_per_app']),f(v['events_per_eventful_appday']),f(v['transitions_per_app']),f(v['ptp_probability'])])
table(['First days','Population','Events/app','Eventful days/app','Events/eventful day','Transitions/app','PTP fraction'],rows)
add('Transitions count adjacent observed events. Histories with missing prerequisites cannot be reproduced by weakening business guards. A supplementary deterministic historical-prefix audit applies the unchanged PD/AIP guards and stops at the first blocked AIP/PTP. It does not fit a stochastic model or replace the raw Phase 2 benchmarks.');add()
rows=[]
for d,z in observable['age'].items():
 for k,v in z.items():rows.append([d,k,f(v['historical_guard_supported_events_per_app']),f(v['simulated_events_per_app']),str([round(x,4) for x in v['combined_app_cluster_95pct_difference']]),f(v['historical_guard_supported_ptp_rate']),f(v['simulated_ptp_rate'])])
table(['Days','Group','Guard-supported history events/app','V2 events/app','95% difference interval','Supported history PTP','V2 PTP'],rows)
add('The preserved, superseded full reference resolves small conditional discrepancies: returning first-day guard-supported activity is about 0.15 events/application higher, and returning conditional PTP is about 1.9–2.8 percentage points higher (statistically resolved, below the declared audit >5pp materiality threshold). Raw returning/new activity remains below the corresponding raw historical benchmarks. Medium confidence checks passed; full-run confidence intervals are reported without claiming every interval includes zero. Lower raw activity and PTP remain disclosed; the missing prerequisite observations explain why the raw PTP target is not an authorized calibration target. See `observable-activity.json` for event and PTP uncertainty.');add()
add('## New-customer and returning-customer applications');add()
rows=[]
for k,z in m['returning']['medium_subpopulations'].items():
 for d,v in z.items():
  for label,key in [('Historical adjusted','historical_weekday_adjusted'),('Corrected-v2','corrected')]:
   w=v[key];rows.append([k,d,label,f(w['events_per_app']),f(w['eventful_appdays_per_app']),f(w['events_per_eventful_appday']),f(w['transitions_per_app']),f(w['ptp_probability'])])
table(['Group','Days','Population','Events/app','Eventful days/app','Events/eventful day','Transitions/app','PTP fraction'],rows)
add('Full arrival schedule: 11,955 returning applications / 48,373 (24.7142%), versus historical eligible April 8,140 / 37,291 (21.8283%). Weekday-adjusted expected May returners: 12,009.53; predictive interval 11,727.31–12,291.75. The generated share is supported by the weekday mixture. All prior owners are real historical contexts, new application IDs are unique and fresh, selected prior lifecycle creation gaps are >=30 days, and no context is reused for two May arrivals. Registry validation enforces no overlap. Historical customer history remains available through the public time-filtered observation. Prior creation gaps, terminal gaps, terminal outcomes and history-depth distributions are in `returning-identity-validation.json`.');add()
add('## Carried applications');add();c=m['carried']['corrected'];add(f"{c['initialized']:,} initialized; {c['active_apps']} active; {c['events']} May rows; {c['ptp_apps']} PTP; {c['expiry_apps']:,} expired; {c['inactive_expiry_apps']:,} expired inactive. Corrected-v1: 37 active, 217 rows, 16 PTP. The audited late-age historical PTP risk has no positive outcomes; corrected-v2 removes unsupported independent-clock PTP rather than preserving that artificial activity.");add();add('Residual survival conditions on weekday/source/age/silence/depth with >=30 unique historical applications and deterministic fallback. Fine near-expiry age bins separate hours from several days of remaining validity. Donors are censored at their exact expiry; the sampled event then competes with the target expiry, avoiding double expiry suppression. One residual draw is persisted per carried episode.');add();add(f"Same Phase 2 Friday/depth benchmark: observed {ci['observed_active']}, expected {ci['expected_active']:.2f}, predictive interval {ci['approx_95pct_predictive_interval']}. Original April1 Wednesday comparison remains separately reported and higher: {m['carried']['matched_april1']['corrected']}. The weekday-sensitive primary gap is a remaining limitation, not a reason to force activity.");add()
e=pd.read_parquet(args.metrics.parent/'simulated_pl.parquet');carry=e.loc[e.creation.lt('2026-05-01')].copy();n=carry.groupby('application_id').size();ad=carry.assign(day=carry.event_datetime.dt.normalize()).groupby(['application_id','day']).size();g=carry.groupby('application_id');s=carry.journey_substage;positive=g.event_datetime.diff().dt.total_seconds().gt(0);counts=dict(eventful_application_days=len(ad),events_per_eventful_day=len(carry)/len(ad),within_may_transitions=int((n-1).clip(lower=0).sum()),reactivation_entry_edges=len(n),self_transitions=int((s.eq(g.journey_substage.shift())&positive).sum()),two_state_cycles=int((s.eq(g.journey_substage.shift(2))&s.ne(g.journey_substage.shift())&positive&(g.event_datetime.shift()-g.event_datetime.shift(2)).dt.total_seconds().gt(0)).sum()),repeated_substage=int(carry.event_datetime.gt(carry.groupby(['application_id','journey_substage']).event_datetime.transform('min')).sum()))
add('Carried May-only counts (entry edge from the historical snapshot is separate): `'+json.dumps(counts)+'`. First-reactivation timing: `'+json.dumps(c['time_to_first_event_hours'])+'` hours.');add()
add('## Loops and revisits');add();rows=[]
for label,w in m['age']['7']['historical_weekday_adjusted']['loops'].items():rows.append([label,f(w['mean_per_app']),f(old['age']['7']['corrected']['loops'][label]['mean_per_app']),f(m['age']['7']['corrected']['loops'][label]['mean_per_app'])])
table(['Count per application, first 7d','Historical adjusted','Corrected-v1','Corrected-v2'],rows)
add('Same-timestamp pairs are not treated as causal cycles. Detailed counts and timing for each new/returning subgroup are in `metrics.json`; carried counters above are May-only. No loop probability was increased.');add()
add('## Subpopulation loop counts and timing');add();rows=[]
for group,ages in m['returning']['medium_subpopulations'].items():
 v=ages['7'];c=v['corrected'];h=v['historical_weekday_adjusted']
 for label in ['self_transition','two_state_cycle','three_state_cycle','repeated_substage','return_to_earlier_stage']:
  rows.append([group,label,c['loops'][label]['events'],f(c['loops'][label]['mean_per_app']),f(h[label+'_per_app'])])
table(['First 7d group','Counter','Simulated count','Simulated/app','Historical adjusted/app'],rows)
rows=[]
for group,ages in m['returning']['medium_subpopulations'].items():
 for label,key in [('Historical','historical_timing'),('Corrected-v2','corrected_timing')]:
  v=ages['7'][key];rows.append([group,label,*[f(v['seconds'][k]) for k in ['p10','p25','median','p75','p90','p95','p99']],f(v['shares']['0']),f(v['shares']['60']),f(v['shares']['300']),f(v['shares']['900']),f(v['shares']['3600']),f(v['over24h'])])
table(['First 7d group','Population','p10','p25','median','p75','p90','p95','p99','Zero','<=1m','<=5m','<=15m','<=1h','>24h'],rows)
add('Subpopulation timing uses equal-age applications; the raw timing distribution is retained. Event activity and PTP comparisons above use weekday adjustment. Metrics also contain first-day and first-three-day subgroup timing.');add()
add('## Timing and finite bursts');add();rows=[]
for label,v in [('Historical',m['timing']['historical']['application']),('Corrected-v1',old['timing']['corrected']['application']),('Corrected-v2',m['timing']['corrected']['application'])]:rows.append([label,*[f(v['seconds'][k]) for k in ['p10','p25','median','p75','p90','p95','p99']],f(v['shares']['0']),f(v['shares']['60']),f(v['shares']['300']),f(v['shares']['900']),f(v['shares']['3600']),f(v['over24h'])])
table(['Population','p10','p25','p50','p75','p90','p95','p99','Zero','<=60s','<=300s','<=900s','<=1h','>24h'],rows)
add('All quantiles are seconds; shares are fractions. Six finite distinct-label patterns have stable March/April support, including Product Selection + Bank Approved and PD Submission + AIP Approved. Canonical ordering puts PD before AIP. Repeated creation instrumentation (94), repeated same-substage tie extras (188), and unsupported co-occurrence extras (944) are excluded. No zero-to-one conversion or jitter. The earlier March/April timing validation reduced AIP→Product Selection CDF error to ~2.2 points, Product Selection→Bank Approved to ~0.2 points, and OTP→PD to ~0.8 points; April is model-selection validation. Rare >24h gaps remain underrepresented.');add()
rows=[]
for source,destination in [('Product Selection','Bank Approved'),('AIP Approved','Product Selection'),('Application OTP Verification','Professional Details Submission'),('Professional Details Submission','AIP Approved'),('Bank Approval Pending','Bank Approved')]:
 for label,block in [('Historical',m['timing']['historical']),('Corrected-v1',old['timing']['corrected']),('Corrected-v2',m['timing']['corrected'])]:
  v=next((z for z in block['by_transition'] if z['source']==source and z['destination']==destination),None)
  if v:rows.append([source+' → '+destination,label,v['n'],f(v['seconds']['median']),f(v['seconds']['p90']),f(v['seconds']['p99'])])
table(['Transition','Population','Observed gaps','Median seconds','p90 seconds','p99 seconds'],rows)
burst=json.loads((args.metrics.parent/'burst-validation.json').read_text());rows=[]
for p in burst['patterns']:rows.append([' + '.join(p['labels']),p['march'],p['april'],p['simulated']])
table(['Supported timestamp pattern','Historical March','Historical April','Current medium aggregate'],rows)
add('Pattern counts above are aggregate support evidence; they are not matched marginal targets. Unsupported simulated timestamp groups: `'+json.dumps(burst['unsupported_simulated_groups'])+'`.');add()
add('## PTP eligibility audit');add();add('Mature March: 44,125 applications; 29,582 with eligible observed AIP; 55,199 eligible AIP episodes; 23,731 eligible PTP episodes. Raw PTP includes 4,335 outcomes without a strictly observed eligible prerequisite sequence. Conditional audit before changing runtime PTP found >7pp frozen young-age CDF errors in both March and April, outside application-cluster uncertainty, and an unsupported late-age global fallback predicting ~62.7% despite zero observed late eligible outcomes. The declared materiality threshold was >5pp conditional error with matching risk competition and uncertainty.');add();add('The preserved pre-gap full-reference eligible-episode young-age CDF is 0.6104 at 300s and 0.6916 at one day, versus historical March/April 0.6211/0.6139 and 0.6995/0.7086. Frozen hazard predicted 0.5424 at 300s and 0.6315 at one day. Late-age simulated eligible episodes have zero PTP, consistent with history. Frozen PTP CSV/donor/manifest files remain byte-identical. Corrected-v2 replaces the independent clock with the joint competing law; no terminal transition is allowed without current-application guards. Raw and observable PTP results are both reported above. Same-time canonical prerequisites explain the small difference between strict-timestamp and executable-order eligibility.');add()
add('## Namespace, external agent and recovery');add();add('Same seed/namespace with different operational run IDs produces identical logical Gold outcomes, including SEND/WAIT and event-name sampling. Different namespaces produce distinct realizations; mismatch is rejected before mutation/recovery. Namespace is persisted in runtime state, checkpoint, run manifest and summary. The medium tail-isolation comparison also proves all 28,405 new Gold rows and cumulative stochastic keys unchanged across operational runs.');add();add('`ExternalAgentSession.observe()` returns only current identifiers, simulated time and customer-scoped Gold-column history through that time. `decide(EnvironmentAction.send(...), next_decision_time)` or `decide(EnvironmentAction.wait(), next_decision_time)` advances organic and pending effects to the caller boundary. Multiple intraday decisions and overnight advances are supported; midnight adds no decision. Separate operator audit is not agent input. Generic core calendar bounds are configurable. Future observation leakage tests pass; pending queue/probabilities never enter observations. Crash-injection recovery tests cover all three commit boundaries, and WAIT segmentation includes carried applications.');add()
add('## Current candidate medium run' if args.medium_candidate else '## Final full-May run');add();add('```json');add(json.dumps(inv,indent=2));add('```');add();add('Seed 20260502; stochastic namespace `corrected-v2-reference-20260502`; operational run ID differs. Day 16 reopened the persisted runner. All 31 daily commit/checkpoint hash links, ownership, exact expiry removals, terminal ordering including ties, and pending boundary clocks are independently checked. No combined historical export or PostgreSQL load was required.');add()
add('## Validation, storage and compatibility');add();add('Full pytest: see `gap-outcome-full-pytest.log`: 90 passed. Focused empirical/contract and artifact-schema tests also pass. Artifact validation covers 31 declared runtime inputs, hashes and required schema. All 58 frozen v1/v2 file hashes remain unchanged. Focused May1 replay matches all three protected daily hashes for both legacy-v2r2 and corrected-v1; the accepted legacy combined SHA remains `7c81a5849d91ad139624bbdba3f9b955f6eba76819b773781acc231f98a4d037`. No additional full legacy run was needed. `git diff --check` passes.');add();add('All important artifacts, reports and run partitions remain on persistent root storage; no instance-store mount or destructive initialization was used. Final local package includes the v3 bundle, run summaries, fidelity evidence, source/code inventory and checksums. Accepted V2r2 S3/PostgreSQL data were untouched.');add()
add('## Known limitations and readiness');add();add('The primary Wednesday carry benchmark remains above the weekday/depth benchmark. Rare tail rates have substantial uncertainty; the carry predictive interval uses a normal cluster-sandwich approximation. Late gaps >24h remain low. Raw PTP is lower because current-application prerequisite observations are incomplete; guards remain authoritative. Returning status means an observed prior March-April lifecycle, not necessarily a first-ever customer otherwise. April was used for validation/model selection. Campaign response assets remain observational.');add()
hp=identity['prior_history_properties'];hv=hp['historical_april'];sv=hp['generated_may'];add(f"Historical April vs corrected candidate prior gap p95: {hv['creation_gap_days']['p95']:.2f} vs {sv['creation_gap_days']['p95']:.2f} days (superseded full bundle: 81.76). Prior PTP: {hv['prior_ptp_fraction']:.4%} vs {sv['prior_ptp_fraction']:.4%}. Historical/generated history-depth quantiles match. Late-May nearest available immutable histories impose a residual gap shift; the audit reports closest available target errors separately. This limitation is retained rather than creating synthetic prior history, reusing contexts, or changing outcomes arbitrarily.");add();add('Independent eligible-donor audit: `'+json.dumps(identity['eligible_donor_validation'])+'`.');add()
if args.medium_candidate:
 add('Transformer readiness: NOT READY to freeze this candidate. Its medium fidelity gate, contract tests and artifacts pass, but the only completed full May used the superseded identity fallback. A second full run is blocked by the user’s explicit ONE final full-run cap and requires approval. The completed reference remains preserved with its exact bundle; it does not certify the current candidate. No additional full run was started.');add()
else:
 add('Transformer readiness: READY for integration under the documented contract and disclosed empirical limitations, subject to user review before freezing.');add()
add('Historical-only empirical fitting; frozen v1/v2 unchanged; accepted V2r2 S3/PostgreSQL untouched; no Transformer/RL integration; no commit/push.');add()
args.report.parent.mkdir(parents=True,exist_ok=True);args.report.write_text('\n'.join(lines)+'\n');print(args.report)
